export const LOADING_CHARACTERS = 'LOADING_CHARACTERS';
export const ERROR_CHARACTERS = 'ERROR_CHARACTERS';
export const FETCH_SUCCESSFULLY_CHARACTERS = 'FETCH_SUCCESSFULLY_CHARACTERS';
export const LOADING_CHARACTER = 'LOADING_CHARACTER';
export const ERROR_CHARACTER = 'ERROR_CHARACTER';
export const FETCH_SUCCESSFULLY_CHARACTER = 'FETCH_SUCCESSFULLY_CHARACTER';